#!/usr/bin/env python
# coding: utf-8

# In[1]:


from pathlib import Path
import re
import json


# In[2]:


#takes all the cells with cell_type code and which have a comment #export on top
def is_export(cell):
    if cell['cell_type'] != 'code': return False
    # this returns a list which is saved in src
    src = cell['source']
    if len(src) == 0 or len(src[0]) < 7: return False
    #import pdb; pdb.set_trace()
    return re.match(r'^\s*#\s*export\s*$', src[0], re.IGNORECASE) is not None


# In[3]:


def notebook2script(fname):
    fname = Path(fname)
    fname_out = f'nb_{fname.stem.split("_")[0]}.py'
    main_dic = json.load(open(fname,'r'))
    code_cells = [c for c in main_dic['cells'] if is_export(c)]
    module = f'''
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/{fname.name}
'''
    for cell in code_cells: module += ''.join(cell['source'][1:]) + '\n\n'
    # remove trailing spaces
    module = re.sub(r' +$', '', module, flags=re.MULTILINE)
    open(fname.parent/'exp'/fname_out,'w').write(module[:-2])
    print(f"Converted {fname} to {fname_out}")


# In[3]:


##Let's break this function down
#fname = Path(fname)
get_ipython().system('ls')


# In[6]:


#Path(fname) returns a PosixPath for MAC and linux
fname = Path("Matmul.ipynb")
fname


# In[7]:


#This is the converted filename we are looking for. We make the name using a f string in python
fname_out = f'nb_{fname.stem.split("_")[0]}.py'
fname_out


# In[8]:


fname.stem


# In[11]:



#Split the string on _ and then take the first index from the resulting list for the output file name
fname.stem.split("_")[0]


# In[12]:


import json


# In[14]:


main_dic = json.load(open(fname,'r'))


# In[15]:


main_dic #load the file as a json object. All jupyter notebooks can be loaded as a json object


# In[16]:


#You have different type of cells here markdown,code etc


# In[17]:


module = f'''
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/{fname.name}
'''  #just a normal f string for comment display


# In[25]:


for cell in main_dic['cells']:
    if cell['cell_type'] == 'code':
        
        
        print(cell)


# In[6]:


get_ipython().run_line_magic('pinfo2', 'Union')


# In[5]:


from typing import *


# In[7]:


class Position:
    def __init__(self,name: str, lon: float = 0.0, lat: float = 0.0, country: str):
        self.name =  name
        self.lon = lon
        self.lat = lat
        self.country = country
        
    


# In[8]:


class Position:
    def __init__(self,name: str,country: str, lon: float = 0.0, lat: float = 0.0, ):
        self.name =  name
        self.lon = lon
        self.lat = lat
        self.country = country


# In[ ]:




